name: update-translation-strings

on:
  - pull_request

jobs:
  update-translation-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Generate the POT file
        run: |
          docker run -v $PWD:/var/www/html --user 1001 --rm wordpress:cli i18n make-pot --ignore-domain ./source languages/free-as-in-speech.pot
          ! git diff --quiet -G'(msgid|msgstr)' || git reset --hard

      - name: Merge changes into the PO files
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          sudo apt-get install gettext
          for po in languages/*.po; do
            echo $po;
            msgmerge -NUv --no-wrap --backup=none $po languages/free-as-in-speech.pot;
            printf '%s\n' "$(cat $po | sed '/^#~ msgid/,/^\s*$/d')" > $po;
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update translation string files.
